#!/bin/bash

aws cloudformation deploy \
    --stack-name stack-builder \
    --template-file $(readlink -f pipeline.yaml) \
    --capabilities CAPABILITY_NAMED_IAM \
    --parameter-overrides ParameterKey=GitHubToken,ParameterValue=$(cat github_oauth_token)
